from flask import Flask, render_template, redirect, url_for, request, send_file
import pymysql, os, subprocess, time

from form import ResumeUploadForm
from utils import get_top_resumes, fetch_candidate_data

app = Flask(__name__, template_folder="template")
app.secret_key = os.environ.get("SECRET_KEY", "secret_key")

@app.route("/", methods=["POST", "GET"])
def form_route():

    mysql_db = {
        "host": "localhost",
        "user": "root",
        "passwd": "",
        "database": "auto_cv"
    }

    db = pymysql.connect(**mysql_db)
    cursor = db.cursor()

    create_table = "CREATE TABLE IF NOT EXISTS cv_data(name VARCHAR(100), contact VARCHAR(20), email VARCHAR(120), resume LONGBLOB)"
    cursor.execute(create_table)

    form = ResumeUploadForm()

    if form.is_submitted():

        name = form.name.data
        contact = form.contact.data
        email = form.email.data
        resume = form.resume.data

        resume_content = resume.read()

        print(name)

        insert_data = "INSERT INTO cv_data VALUES(%s, %s, %s, %s)"
        values = (name, contact, email, resume_content)

        cursor.execute(insert_data, values)
        db.commit()
        cursor.close()
        db.close()

        return redirect(url_for("recorded_response"))

    return render_template("upload.html", form=form)

@app.route("/recorded_response")
def recorded_response():

    return render_template("success.html")

@app.route("/dashboard")
def dashboard():

    applicants = []

    path = r"D:\Programs\Hackathon\cuda-recruitment-system\scores.csv"
    resumes, scores = get_top_resumes(path)

    names, contacts, emails = fetch_candidate_data()

    for i in range(len(scores)):

        applicant = {
            "name": names[i],
            "resume_url": resumes[i],
            "match_percentage": round(scores[i] * 10, 4),
            "contact": contacts[i],
            "email": emails[i]
        }

        applicants.append(applicant)

    return render_template("dashboard.html", applicants=applicants)

@app.route('/api/download-resume', methods=['POST'])
def download_resume():
    data = request.json
    file_path = data.get('file_path')
    applicant_name = data.get('applicant_name')

    print(file_path)
    
    # Security: Validate the file path to prevent directory traversal
    if not os.path.exists(file_path):
        return {'error': 'File not found'}, 404
    
    # Serve the file
    return send_file(
        file_path,
        as_attachment=True,
        download_name=f"{applicant_name.replace(' ', '_')}_resume"
    )

@app.route("/process")
def process():

    base_dir = "D:/Programs/Hackathon/cuda-recruitment-system"

    src_dir = os.path.join(base_dir, "src")
    core_path = os.path.join(src_dir, "recruit.exe")

    print("Binary exists:", os.path.exists(core_path))
    print("CWD:", src_dir)


    with open(os.path.join(base_dir, "logs.txt"), "w") as log:
        s_id = subprocess.run(
            [core_path, "../cleaned_resumes", "../target/target.bin"],
            cwd=os.path.join(base_dir, "src"),
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True
        )

    scores_path = os.path.join(base_dir, "scores.csv")

    for _ in range(10):
        if os.path.exists(scores_path):
            break
        time.sleep(1)
    else:
        raise RuntimeError("scores.csv was not generated by recruit.exe")


    if s_id.returncode != 0:
            raise RuntimeError("Resume processing failed!: " + s_id.stderr)
    else:
        return redirect(url_for("dashboard"))
